services:
  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    # node_modules をホストと分離するマウント指定にする
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app